package net.runelite.client.plugins.microbot.aiobot.enums;

public enum QuestType {
    // Free-to-Play Quests
    COOKS_ASSISTANT("Cook's Assistant"),
    DEMON_SLAYER("Demon Slayer"),
    THE_RESTLESS_GHOST("The Restless Ghost"),
    ROMEO_AND_JULIET("Romeo & Juliet"),
    SHEEP_SHEARER("Sheep Shearer"),
    SHIELD_OF_ARRAV("Shield of Arrav"),
    ERNEST_THE_CHICKEN("Ernest the Chicken"),
    VAMPYRE_SLAYER("Vampyre Slayer"),
    IMP_CATCHER("Imp Catcher"),
    PRINCE_ALI_RESCUE("Prince Ali Rescue"),
    DORICS_QUEST("Doric's Quest"),
    BLACK_KNIGHTS_FORTRESS("Black Knights' Fortress"),
    WITCHS_POTION("Witch's Potion"),
    KNIGHTS_SWORD("The Knight's Sword"),
    GOBLIN_DIPLOMACY("Goblin Diplomacy"),
    PIRATES_TREASURE("Pirate's Treasure"),
    DRAGON_SLAYER_I("Dragon Slayer I"),
    WITCHS_HOUSE("Witch's House"),
    MISTHALIN_MYSTERY("Misthalin Mystery"),
    CORSAIR_CURSE("The Corsair Curse"),
    X_MARKS_THE_SPOT("X Marks the Spot"),
    BELOW_ICE_MOUNTAIN("Below Ice Mountain"),

    // Members Quests
    DRUIDIC_RITUAL("Druidic Ritual"),
    LOST_CITY("Lost City"),
    MERLIN_CRYSTAL("Merlin's Crystal"),
    HEROES_QUEST("Heroes' Quest"),
    SCORPION_CATCHER("Scorpion Catcher"),
    FAMILY_CREST("Family Crest"),
    TRIBAL_TOTEM("Tribal Totem"),
    FISHING_CONTEST("Fishing Contest"),
    MONKS_FRIEND("Monk's Friend"),
    TEMPLE_OF_IKOV("Temple of Ikov"),
    CLOCK_TOWER("Clock Tower"),
    HOLY_GRAIL("Holy Grail"),
    FIGHT_ARENA("Fight Arena"),
    TREE_GNOME_VILLAGE("Tree Gnome Village"),
    THE_HAZEEL_CULT("The Hazeel Cult"),
    SHEEP_HERDER("Sheep Herder"),
    PLAGUE_CITY("Plague City"),
    SEA_SLUG("Sea Slug"),
    WATERFALL_QUEST("Waterfall Quest"),
    BIOHAZARD("Biohazard"),
    JUNGLE_POTION("Jungle Potion"),
    GRAND_TREE("The Grand Tree"),
    SHILO_VILLAGE("Shilo Village"),
    UNDERGROUND_PASS("Underground Pass"),
    OBSERVATORY_QUEST("Observatory Quest"),
    TOURIST_TRAP("Tourist Trap"),
    WATCHTOWER("Watchtower"),
    DWARF_CANNON("Dwarf Cannon"),
    MURDER_MYSTERY("Murder Mystery"),
    DIGSITE("The Digsite"),
    GERTRUDES_CAT("Gertrude's Cat"),
    LEGENDS_QUEST("Legends' Quest"),
    RUNE_MYSTERIES("Rune Mysteries"),
    BIG_CHOMPY_BIRD_HUNTING("Big Chompy Bird Hunting"),
    ELEMENTAL_WORKSHOP_I("Elemental Workshop I"),
    PRIEST_IN_PERIL("Priest in Peril"),
    NATURE_SPIRIT("Nature Spirit"),
    DEATH_PLATEAU("Death Plateau"),
    TROLL_STRONGHOLD("Troll Stronghold"),
    TAI_BWO_WANNAI_TRIO("Tai Bwo Wannai Trio"),
    REGICIDE("Regicide"),
    EADGARS_RUSE("Eadgar's Ruse"),
    SHADES_OF_MORTTON("Shades of Mort'ton"),
    FREMENNIK_TRIALS("The Fremennik Trials"),
    HORROR_FROM_THE_DEEP("Horror from the Deep"),
    THRONE_OF_MISCELLANIA("Throne of Miscellania"),
    MONKEY_MADNESS_I("Monkey Madness I"),
    HAUNTED_MINE("Haunted Mine"),
    TROLL_ROMANCE("Troll Romance"),
    IN_SEARCH_OF_THE_MYREQUE("In Search of the Myreque"),
    CREATURE_OF_FENKENSTRAIN("Creature of Fenkenstrain"),
    ROVING_ELVES("Roving Elves"),
    GHOSTS_AHOY("Ghosts Ahoy"),
    ONE_SMALL_FAVOUR("One Small Favour"),
    MOUNTAIN_DAUGHTER("Mountain Daughter"),
    BETWEEN_A_ROCK("Between a Rock..."),
    FEUD("The Feud"),
    GOLEM("The Golem"),
    DESERT_TREASURE_I("Desert Treasure I"),
    ICTHLARIN_LITTLE_HELPER("Icthlarin's Little Helper"),
    TEARS_OF_GUTHIX("Tears of Guthix"),
    ZOGRE_FLESH_EATERS("Zogre Flesh Eaters"),
    LOST_TRIBE("The Lost Tribe"),
    GIANT_DWARF("The Giant Dwarf"),
    RECRUITMENT_DRIVE("Recruitment Drive"),
    MOURNINGS_END_PART_I("Mourning's End Part I"),
    FORGETTABLE_TALE("Forgettable Tale..."),
    GARDEN_OF_TRANQUILLITY("Garden of Tranquillity"),
    TREE_GNOME_STRONGHOLD("Tree Gnome Stronghold"),
    HAND_IN_THE_SAND("The Hand in the Sand"),
    MOURNINGS_END_PART_II("Mourning's End Part II"),
    CONTACT("Contact!"),
    CABIN_FEVER("Cabin Fever"),
    ROYAL_TROUBLE("Royal Trouble"),
    DARKNESS_OF_HALLOWVALE("Darkness of Hallowvale"),
    RECIPE_FOR_DISASTER("Recipe for Disaster"),
    WANTED("Wanted!"),
    LUNAR_DIPLOMACY("Lunar Diplomacy"),
    WHAT_LIES_BELOW("What Lies Below"),
    SLUG_MENACE("The Slug Menace"),
    ELEMENTAL_WORKSHOP_II("Elemental Workshop II"),
    MY_ARMS_BIG_ADVENTURE("My Arm's Big Adventure"),
    ENLIGHTENED_JOURNEY("Enlightened Journey"),
    EAGLES_PEAK("Eagles' Peak"),
    ANIMAL_MAGNETISM("Animal Magnetism"),
    COLD_WAR("Cold War"),
    FREMENNIK_ISLES("The Fremennik Isles"),
    TOWER_OF_LIFE("Tower of Life"),
    GREAT_BRAIN_ROBBERY("The Great Brain Robbery"),
    WHAT_CAME_BEFORE("What Came Before?"),
    BONE_VOYAGE("Bone Voyage"),
    CLIENT_OF_KOUREND("Client of Kourend"),
    DEPTHS_OF_DESPAIR("The Depths of Despair"),
    DRAGON_SLAYER_II("Dragon Slayer II"),
    TALE_OF_THE_RIGHTEOUS("Tale of the Righteous"),
    ARCHITECTURAL_ALLIANCE("Architectural Alliance"),
    QUEEN_OF_THIEVES("The Queen of Thieves"),
    LOVING_OF_KOUREND("The Loving of Kourend"),
    ASCENT_OF_ARCEUUS("The Ascent of Arceuus"),
    FORSAKEN_TOWER("The Forsaken Tower"),
    MAKING_FRIENDS_WITH_MY_ARM("Making Friends with My Arm"),
    SONG_OF_THE_ELVES("Song of the Elves"),
    FREMENNIK_EXILES("The Fremennik Exiles"),
    SINS_OF_THE_FATHER("Sins of the Father"),
    GETTING_AHEAD("Getting Ahead"),
    NIGHT_AT_THE_THEATRE("A Night at the Theatre"),
    KINGDOM_DIVIDED("A Kingdom Divided"),
    TASTE_OF_HOPE("A Taste of Hope"),
    PORCINE_OF_INTEREST("A Porcine of Interest"),
    BELOW_THE_ICE("Below the Ice"),
    TEMPLE_OF_THE_EYE("Temple of the Eye"),
    BENEATH_CURSED_SANDS("Beneath Cursed Sands"),
    DESERT_TREASURE_II("Desert Treasure II"),
    SECRETS_OF_THE_NORTH("Secrets of the North"),
    CHILDREN_OF_THE_SUN("Children of the Sun"),
    DEFENDER_OF_VARROCK("Defender of Varrock"),
    PERILOUS_MOONS("Perilous Moons"),
    AT_FIRST_LIGHT("At First Light"),
    WHILE_GUTHIX_SLEEPS("While Guthix Sleeps");

    private final String displayName;

    QuestType(String displayName) {
        this.displayName = displayName;
    }

    public String getDisplayName() {
        return displayName;
    }
}